[build]
  publish = "public"
  functions = "built-lambda"

[build.environment]
  # Environment variables are set here
  NODE_VERSION = "20"

[[redirects]]
  from = "/shorten"
  to = "/.netlify/functions/shorten"
  status = 200

[[redirects]]
  from = "/count"
  to = "/.netlify/functions/count"
  status = 200

[[redirects]]
  from = "/latest"
  to = "/.netlify/functions/latest"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect/:splat"
  status = 200
  methods = ["GET"]

[[redirects]]
  from = "/"
  to = "/.netlify/functions/redirect/:splat"
  status = 200
  methods = ["GET"]