[build]
  functions = "built-lambda"

[[redirects]]
  from = "/shorten"
  to = "/.netlify/functions/url-shortener"
  status = 200
  methods = ["POST"]

[[edge_functions]]
  path = "/latest-edge"
  function = "latest-edge"

[[edge_functions]]
  path = "/count-edge"
  function = "count-edge"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/url-shortener/:splat"
  status = 200
  methods = ["GET"]

[[redirects]]
  from = "/"
  to = "/index.html"  # Redirect root URL to index.html
  status = 200
  methods = ["GET"]

  